### ISSUE TITLE
Issue getting sapl.bom

### ISSUE THREAD

**Issue by mtj8033** [heutelbeck/sapl-demos#23]
Is there anything special we need to do for setup when downloading the demos repo?

Could not transfer artifact io.sapl:sapl-bom:pom:2.0.0-SNAPSHOT from/to sapl (https://maven.pkg.github.com/heutelbeck/packages): Not authorized

**Comment by heutelbeck** [comment]
Hello, during the last days, I have been migrating hosting of all maven artifacts from a self-hosted maven repository to GitHub packages. Unfortunately there is one issue with that. You cannot download the artifacts without authenticating with GitHub. I think this is unfortunate, but it is what it is at the moment. As soon as we have a first 2.0.0 release we will push to central.

I also adjusted the documentation of the packages repository accordingly. (https://github.com/heutelbeck/packages)

Please generate a personal access token for your GitHub account and add this to your ```~/.m2/settings.xml```:

```
   </servers>
      <server>
         <id>sapl</id>
         <username>USERNAME</username>
         <!-- see https://github.com/settings/tokens -->
         <password>ACCESS TOKEN</password>
      </server>
   </servers>
```

I am very interested in how and why you are evaluating SAPL. So lets talk if you won't mind. Also this is a relatively complex project and I am happy to help with anything here.

**Comment by heutelbeck** [comment]
Hello, Michael,

I just migrated the artifacts to Maven Central, i.e., the snapshots now reside on the public Sonatype Snapshots repositories, and the release will be on central. No authentication is required. For the demos, just pull and build.

```xml
	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
```
