### ISSUE TITLE
[sapl-demo-playground] Playground does not react on the first three changed char's

### ISSUE THREAD

**Issue by nniikkoollaaii** [heutelbeck/sapl-demos#36]
After page load the sapl-editor-for-vaadin components "sapl-editor" & "json-editor" are not emitting a DocumentChangedEvent for the first three changes.

Because of this the playground is not removing the result of the previous run if for example a single semicolon in the policy is removed, making the policy invalid.

During debugging via a Console.log statement here <https://github.com/heutelbeck/sapl-server/blob/main/sapl-editor-for-vaadin/src/main/resources/META-INF/frontend/json-editor.js#L96>
I could observe, that the javascript onDocumentChanged method is called on every change. But it's somehow not forwarding this correctly to vaadin.

You can recreate this behaviour on https://playground.sapl.io

**Comment by nniikkoollaaii** [comment]
Hi @Nipahu , 
could you please provide some help here?
I'm currently having no idea, why the Sapl-Editor-for-Vaadin components aren't throwing the DocumentChangedEvent correctly :/.

**Comment by Nipahu** [comment]
Hi @nniikkoollaaii I will take a look at this this weekend. Currently I'm not sure why its behaving this way.

**Comment by Nipahu** [comment]
I have taken a look at it and the problem seems to be with `ignoreUIChanges` in the `ContentView` class. This integer field is counted down when changes are made and is set to 3. If I set to 0 or put the logging before the check the event fires completely normal for me. It doesn't seem to be a bug in the editior.

**Comment by nniikkoollaaii** [comment]
Oh! My mistake!

I tried to prevent the playground calculating the decision three times after setting the inital example (updating the three editor components).
Probably this stopped working with one of my last changes and instead caused this bug.

I'm very sorry I bothered you with this.

Thank you for your help!
