### ISSUE TITLE
Build of sapl-demo-reactive is failing

### ISSUE THREAD

**Issue by nniikkoollaaii** [heutelbeck/sapl-demos#41]
Hello @heutelbeck , 

the build of the sapl-demo-reactive component is failing. Probably due to your version bump this afternoon?

This is since some change you introduced somewhere triggering this build:

<https://github.com/heutelbeck/sapl-demos/actions/runs/1005360953>

Could you please have a look?

**Comment by heutelbeck** [comment]
Caused by a bad dependency setting in the new sapl-generator module unrelated to my pushes. I pushed a fix to the engine.
