### ISSUE TITLE
ERROR[Type mismatch. Can only access arrays by index, got: Value[undefined]]

### ISSUE THREAD

**Issue by rohitranjan1991** [heutelbeck/sapl-demos#50]
@heutelbeck, First of all thanks for the awesome library. Cab you please quickly help me with this.

I am getting the error 
`ERROR[Type mismatch. Can only access arrays by index, got: Value[undefined]]`

My Sapl file is 

> import filter.*
> 
> set "KubernetesResourceKindController"
> 
> first-applicable
> 
> for "KubernetesResourceKindController" in action.java.instanceof..simpleName
> 
> policy "create Kubernetes kind only if user has access to organisation and workspace"
> permit action.java.name == "createKubernetesResourceKind"
> where
>     subject.name == action.arguments[1].<krk.accessToOrganisation>;

And this is my Spring boot Controller code snipped

>   @PostMapping("")
>     @IsDevopsOrAbove
>     @PreEnforce
>     fun createKubernetesResourceKind(
>         @RequestHeader("organisationId") organisationId: String,
>         @RequestHeader("workspaceId") workspaceId: String,
>         @RequestBody createKubernetesResourceKindRequest: CreateKubernetesResourceKindRequest,
>     ): ResponseEntity<CustomAPIResponse> {
>         val result = kubernetesResourceKindService.createKubernetesResourceKind(

My PIP file looks like this

> @Service
> @PolicyInformationPoint(name = "krk", description = "retrives info related to KRK")
> class OrganisationPIP {
> 
>     @Autowired
>     lateinit var workspaceService: WorkspaceService
> 
>     @Autowired
>     lateinit var userService: UserService
> 
> 
>     @Attribute(name = "accessToOrganisation")
>     fun getAccessOfUserToOrganisation(@Array organisationId: Val, variables: Map<String, JsonNode>): Flux<Val> {
>         println("Called getAccessOfUserToOrganisation")
>         return Flux.just(Val.of(Utils.objectMapper.convertValue(mapOf("abc" to "bca"), JsonNode::class.java)))
>     }
> 
> }

**Comment by heutelbeck** [comment]
First, thanks for giving SAPL a try. I am happy to look into it.

I suspect the following:

The wording of the error message may not be precise enough.

```ERROR[Type mismatch. Can only access arrays by index, got: Value[undefined]]``` means that you are trying to access something with the [index] operator that is not an array. And what you are attempting to access is an ```undefined``` value ```"Value[undefined]]"```.

Thus, ```action.arguments``` is not defined in your authorization subscription and returns an ```undefined```. This is a special value similar to something like null/nil/NaN etc., that allows for reasoning about undefined values in JSON objects in a policy.

By default, SAPL writes the arguments to ```action.java.arguments```.

Change: ```action.arguments[1]``` to ```action.java.arguments[1]```

This change should do the trick. Please let me know if this was the issue.

I just updated the error message to be clearer in the current snapshot: ```"Type mismatch. The [index] access operator can only be applied to arrays. However, the policy actually attempted to apply the operator to: %s"```.

Please let me know if I can be of any more help.

**Comment by rohitranjan1991** [comment]
Ahh Thanks a lot .. That worked :-) I couldn't find any such examples in the demo repository. Thanks again :-)

**Comment by rohitranjan1991** [comment]
https://github.com/heutelbeck/sapl-demos/issues/50

**Comment by heutelbeck** [comment]
No, there was none. But it is a good idea. So now there is: https://discord.gg/Vh7UvBk9
